[workspace]
resolver = "2"
members = ["crates/burn", "crates/burn-runtime", "crates/bvm"]

[workspace.package]
version = "26.1.0-experimental-2"
edition = "2021"
license = "GPL-3.0-only"
rust-version = "1.85"
repository = "https://github.com/burnlang/burn"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 4
panic = "unwind"
